[workspace]

members = [
    "p2235_add_two_integers",
    "p2236_root_equals_sum_of_children",
    "p226_invert_binary_tree",
    "p1480_running_sum_of_1d_array",
    "p1672_richest_customer_wealth",
    "p412_fizz_buzz",
    "p1342_number_of_steps_to_reduce_a_number_to_zero",
    "p876_middle_of_the_linked_list",
    "p383_ransom_note",
    "l0001_smart_pointers",
]
