[workspace]

members = [
    "l0000_rust_playground",
    "p2235_add_two_integers",
    "p2236_root_equals_sum_of_children",
    "p226_invert_binary_tree",
    "p1480_running_sum_of_1d_array",
    "p1672_richest_customer_wealth",
    "p412_fizz_buzz",
    "p1342_number_of_steps_to_reduce_a_number_to_zero",
    "p876_middle_of_the_linked_list",
    "p383_ransom_note",
    "l0001_smart_pointers",
    "l0002_fibonacci",
    "l0003_is_palindrome",
    "l0004_is_there_pair_that_sums_target",
    "l0005_combine_sorted",
    "p392_is_subsequence",
    "p344_reverse_string",
    "p977_squares_of_a_sorted_array",
    "l0006_sliding_window",
    "p713_subarray_product_less_than_k",
    "p643_maximum_average_subarray_i",
    "p1004_max_consecutive_ones_iii",
    "l0006_prefix_sum",
    "p2270_number_of_ways_to_split_array",
    "p1413_minimum_value_to_get_positive_step_by_step_sum",
    "p557_reverse_words_in_a_string_iii",
]
