[workspace]

members = [
    "p2235_add_two_integers",
    "p2236_root_equals_sum_of_children",
    "p226_invert_binary_tree",
    "p1480_running_sum_of_1d_array",
    "p1672_richest_customer_wealth",
    "p412_fizz_buzz",
    "l0001_smart_pointers",
]
